[pg] we need to return the promise (#168)
our `query` shim was executing the query properly if instrumentation was active, but it wasn't returning the promise back, leading to

```
TypeError: Cannot read property 'then' of undefined
```

This should fix things.